export const legalCasesData = [
    {
        caseName: "Sharma v. Tech Innovations Pvt. Ltd.",
        caseNo: "CWP-2024-1234",
        status: "Ongoing",
        regdate: "05.03.2024",
        client: "Rahul Sharma",
        category: "Labour Law",
      },
      {
        caseName: "Green India Ltd. v. EcoSolutions Corp.",
        caseNo: "CS-2024-5678",
        status: "Closed",
        regdate: "12.01.2024",
        client: "Green India Ltd.",
        category: "Commercial Dispute",
      },
      {
        caseName: "Patel v. Maharashtra State Electricity Board",
        caseNo: "WP-2024-9101",
        status: "Ongoing",
        regdate: "15.10.2024",
        client: "Anjali Patel",
        category: "Public Interest Litigation",
      },
      {
        caseName: "State of Karnataka v. Kumar",
        caseNo: "CRL-2024-1121",
        status: "Pending",
        regdate: "22.04.2024",
        client: "Arjun Kumar",
        category: "Criminal",
      },
      {
        caseName: "In re: Chopra Family Trust",
        caseNo: "TA-2024-3141",
        status: "Ongoing",
        regdate: "30.06.2024",
        client: "Chopra Family",
        category: "Testamentary",
      },
      {
        caseName: "Singh v. Municipal Corporation of Delhi",
        caseNo: "CWP-2024-5161",
        status: "Pending",
        regdate: "18.07.2024",
        client: "Gurpreet Singh",
        category: "Administrative Law",
      },
      {
        caseName: "Mehta v. National Insurance Co. Ltd.",
        caseNo: "CC-2024-7181",
        status: "Closed",
        regdate: "09.02.2024",
        client: "Priya Mehta",
        category: "Consumer Dispute",
      },
      {
        caseName: "Reddy v. Reddy",
        caseNo: "HMA-2024-9202",
        status: "Ongoing",
        regdate: "03.05.2024",
        client: "Kavita Reddy",
        category: "Family Law",
      }
  ];
